### ISSUE TITLE
What's that, mate?

### ISSUE THREAD

**Issue by omiroshn** [fotonmoton/uf_abm#23]

**Comment by fotonmoton** [comment]
This is an [agent based model](https://en.wikipedia.org/wiki/Agent-based_model) of the UNIT in which `Student` is a process that has some behavior and can communicate to another processes like `Intra` or another `Student`. "Just for fun" project to learn some Elixir. If you want you can also contribute! We don't have any strict plans for it so feel free to add functionality you want to see.

**Comment by omiroshn** [comment]
i would love to.
for that, i think, firstly, i need to learn Exilir, lmbao

**Comment by fotonmoton** [comment]
You can learn by tinkering with this project :) I would suggest you look up [Elixir getting started](https://elixir-lang.org/getting-started/introduction.html) guide, it's pretty cool and informative

**Comment by omiroshn** [comment]
![elixir](https://www.hannahrhodes.co/wp-content/uploads/2018/05/bigelixir_gif.gif)
